### ISSUE TITLE
BBC not resuming (BBC Sounds)

### ISSUE THREAD

**Issue by Sh4nd2** [TheFes/HA-configuration#104]
I saw the latest version included support for bbc (sounds and iplayer) and with delight updated. But i just cant get it to work, definitely appears to be BBC specific, (tuneitin still resumes fine). Any help would be greatly appreciated.

my old hacky method doesnt work either so i'm not sure if a home assistant update has knackered the way of pushing bbcsounds app through.

[trace script.google_home_resume_helper 2023-10-27T21_09_07.427604+00_00.json](https://github.com/TheFes/HA-configuration/files/13193515/trace.script.google_home_resume_helper.2023-10-27T21_09_07.427604%2B00_00.json)
[trace script.google_home_resume 2023-10-27T21_09_05.855123+00_00.json](https://github.com/TheFes/HA-configuration/files/13193516/trace.script.google_home_resume.2023-10-27T21_09_05.855123%2B00_00.json)

**Comment by Sh4nd2** [comment]
this seems related to https://github.com/home-assistant/core/issues/101151

basically playing bbc radio direct from a service call on home assistant seems to be on the blink thanks to some decisions made at BBC. i wont pretend i understand, and it may be that individuals smarter then me will solve it yet but no easy solution.

**Comment by TheFes** [comment]
Nothing I can do on my end, looks like this PR needs to be merged
https://github.com/home-assistant-libs/pychromecast/pull/753
