### ISSUE TITLE
Verbinden met Google Home

### ISSUE THREAD

**Issue by JackyHallo** [TheFes/HA-configuration#105]
Hi,

Ik hoop dat het oke is dat ik het even in het NL doe..

Ik probeer mijn Google Home te laten werken met HA voor het besturen van de verlichting, maar krijg het niet aan het werken.
Momenteel gebruik ik Pyloxone al (domotica Loxone), maar krijg het niet zo ver dat Google Home commands verstuurt naar HA.

Als er betere manieren of dergelijke zijn mag u dit altijd laten weten..

**Comment by TheFes** [comment]
Dit is niet iets waarmee ik kan helpen. Ik raad je aan om het op de Home Assistant Discord of op Facebook te vragen
