### ISSUE TITLE
Google Home Resume: tts.google_say / tts.speak --- setting announce volume

### ISSUE THREAD

**Issue by servernotifiche** [TheFes/HA-configuration#108]
Hi, and tanks for your work!
I'm trying to get the script to work, but I'm having some difficulties.
Im not using nabucasa, so for tts im using tts.google_say (google_translate): when I launch the script, Spotify stops but no tts is played and even after some time Spotify doesn't start again; this is the error message: "Invocazione del servizio script.google_home_resume non riuscita. CastMediaPlayerEntity.media_stop Failed: Execution of stop timed out after 10.0 s.". why??? (I have all the scripts using this one).
So I tried using tts.speak, the tts message plays and spotify starts again correctly. Is there a way to set the playback volume of the TTS?
thanks in advance.

Daniele

**Comment by TheFes** [comment]
I have a dedicated repo for the script. Your issue has already being discussed here
https://github.com/TheFes/Google-Home-Resume/issues/8

There is a setting for the TTS volume, you can find it in the documentation on that repo

I'm currently on mobile, while on holiday, so it's a bit troublesome to give up the exact link now. 

I'll close this issue now, as it seems the same as the linked issue
