### ISSUE TITLE
Single accounts not supported 

### ISSUE THREAD

**Issue by Honest-Objections** [TheFes/HA-configuration#20]
First off, HUGE thank you for taking the time to make this. It's been a pita having to restart music everytime so I find myself sitting in silence. I'm sure I'll enjoy using this even more than your kids. 

First question, is there anyway this could be a python script? You must have had the patience of a saint writing the yaml, but I can't really follow it. If you know a way to make it a script I'd happily contribute! (very keen to support the BBC, which is no longer via tunein)

Second question:

```shell
2022-04-08 23:26:36 ERROR (MainThread) [homeassistant.components.script.google_home_resume_perform_resume] 00 🔊 Google Home Resume - Perform resume: Resume needed?: choice 1: Resume playing: Spotify?: Primary spotcast account?: default: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 372, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 575, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 170, in start_casting
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 179, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 170, in get_token_instance
    dc = self.accounts.get(account).get(CONF_SP_DC)
AttributeError: 'NoneType' object has no attribute 'get'
```

I've been struggling to debug what's going on. Here's the variables I can find:

```yaml
spotify_data:
  - entity_id: media_player.spotify_xxxxx_xxxxx
    source: Landing speaker
player_data:
  - data_source: resume_script
    entity_id: media_player.landing_speaker
    state: playing
    app_name: Spotify
    volume_level: 0.44998854398727417
    media_position: 19.155000047683714
    members: []
    type: no screen
    spotcast: xxxx_xxxxx
players_to_resume:
  - media_player.landing_speaker
```

I've masked my account, but it seems sensible. I don't really know where to go from here? My spotcast works via the lovelace attachment and I've removed `default_user` from the variables.

Any thoughts? And thanks again!

**Comment by Honest-Objections** [comment]
Having articulated it, I assume this may be an issue with `spotcast` being setup as a single user, rather than multiple users (given there is an option for `default_user`) 

```python
self.accounts.get(account).get(CONF_SP_DC)
```

**Comment by Honest-Objections** [comment]
Now working! The `accounts` key is indeed required. For any other users, this is the minimum required config for spotcast

```yaml
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: SE #optional, added in 3.6.24
  accounts:
    niklas:
      sp_dc: !secret niklas_sp_dc
      sp_key: !secret niklas_sp_key
```

**Comment by TheFes** [comment]
Actually it isn't, it works without the `account` in the Spotcast setup.

You've masked the actual spotify media_player, but let's say it's: `media_player.spotify_honest_objections`

To make it work without the account in the Spotcast setup, you need to provide the correct `primary_spotcast` in the script setup. That's where this variable is used for.

For the media_player above, it should be
 ```yaml
primary_spotcast: honest_objections
```

**Comment by TheFes** [comment]
Regarding the python script, I don't have a programming background. All I know I learned using Home Assistant, so basically I can only write YAML and jinja.

While Jinja is quite similar to python I might look into that a bit further in the future, but I don't expect I will have much time on my hands in the coming years even.

**Comment by TheFes** [comment]
You did gave me some ideas to improve the single Spotify account setup, which I will implement when working on this issue:
https://github.com/TheFes/HA-configuration/issues/22

**Comment by Honest-Objections** [comment]
Amazing! You're right of course, I was having other issues that didn't seem to produce much of a trace, so took all the variables out. Thanks again for sharing your hard work
