### ISSUE TITLE
Template warning/error

### ISSUE THREAD

**Issue by besiktas97** [TheFes/HA-configuration#46]
Hey TheFes,

I am using your script for a while now and it still doing a very good job.
One thing that I see in my logs is the following:

Logger: homeassistant.helpers.template
Source: helpers/template.py:1850 
First occurred: June 15, 2022, 23:22:00 (1 occurrences) 
Last logged: June 15, 2022, 23:22:00

Template variable warning: 'players_screen' is undefined when rendering '{{ [] if not players_screen else target_not_playing | select('in', players_screen) | list }}'

I dont think that I need to worry about, but will it gives any problems for in the future if you know?
I don’t have the line players_screen, because I don’t need it. Or can I just add the line without any argument, so that the error doesn’t show anymore?

greetings,

Besiktas97

**Comment by TheFes** [comment]
Sorry, I missed this post.
I will look into it, should be an easy fix!

**Comment by TheFes** [comment]
Could you send me a trace of the script run from which you get this error? 
I think you are on a older version, because I can't find this template mentioned in the current version.

**Comment by besiktas97** [comment]
No problem, everything is still working perfect ghehe.
When I say show trace, I get below:

alias: Set variables to be used in the script
variables:
  target_list: |
    {% if voice_tts_target is defined %}
      {{ [ voice_tts_target ] }}
    {% else %}
      {# determine entities of cast integraton #}
        {%- set devices = states | map(attribute='entity_id') | map('device_id') | unique | reject('eq',None) | list %}
        {%- set ns = namespace(entities = []) %}
        {%- for device in devices %}
          {%- set ids = device_attr(device, 'identifiers') | list | first %}
          {%- if ids and ids | length == 2 and ids[0] == 'cast' %}
            {%- set ns.entities = ns.entities + device_entities(device) %}
          {%- endif %}
        {%- endfor %}
        {% set cast_entities = ns.entities %}
      {# create target lists #}
      {% if target is defined %}
        {# create lists based on target input #}
          {% set area_list = target.area_id.replace(' ' , '').split(',') if target.area_id is string else target.area_id %}
          {% set device_list = target.device_id.replace(' ' , '').split(',') if target.device_id is string else target.device_id %}
          {% set entity_list = target.entity_id.replace(' ' , '').split(',') if target.entity_id is string else target.entity_id %}
      {% else %}
        {# determine targets based on actions if target not specified #}
          {% set ns = namespace(entity = [], device = [], area = [] ) %}
          {% for item in action %}
            {% set entity = item.target.get('entity_id', []) %}
            {% set device = item.target.get('device_id', []) %}
            {% set area = item.target.get('area_id', []) %}
            {% set ns.entity = ns.entity + [ entity ] if entity is string else entity %}
            {% set ns.device = ns.device + [ device ] if device is string else device %}
            {% set ns.area = ns.area + [ area ] if area is string else area %}
          {% endfor %}
          {% set area_list = ns.area %}
          {% set device_list = ns.device %}
          {% set entity_list = ns.entity %}
      {% endif %}
      {# create entity list based on device/area input #}
        {# determine cast entities of areas #}
          {% set ns = namespace(area_cast = []) %}
          {% for area in area_list %}
            {% set ns.area_cast = ns.area_cast + area_entities(area) | select('in', cast_entities) | list %}
          {% endfor %}
          {% set area_cast = ns.area_cast %}
        {# determine cast entities of devices #}
          {% set ns = namespace(device_cast = []) %}
          {% for device in device_list %}
            {% set ns.device_cast = ns.device_cast + device_entities(device) | select('in', cast_entities) | list %}
          {% endfor %}
          {% set device_cast = ns.device_cast %}
      {# create list with all entities #}
        {{ (area_cast + device_cast + entity_list) | unique | list }}
    {% endif %}
  speaker_group_list: '{{ speaker_groups.keys() | list if speaker_groups is defined else [] }}'
  players_to_resume: |
    {# use data from google_home_say_voice script in case it was used #}
      {% if voice_media_player_data is defined %}
        {{ voice_media_player_data }}
      {% else %}
        {# determine which media_players are playing and store attributes#}
          {% 
            set all_players_playing = states.media_player 
                                        | selectattr('state', 'eq', 'playing') 
                                        | map(attribute='entity_id') 
                                        | list  
          %}
    {# determine which Google Home speakers groups are playing #}
          {% 
            set all_speaker_groups_playing =  voice_groups | default(
                                              all_players_playing 
                                                | select('in', speaker_group_list) 
                                                | list )
          %}
        {# determine which of the targets (including groups members) are playing  #}
          {% set ns = namespace(targets = []) %}
            {% for target in target_list %}
              {% set ns.targets = ns.targets +  (
                                                          speaker_groups[target] 
                                                          if target in speaker_group_list 
                                                          else [ target ] 
                                                        ) 
              %}
            {% endfor %}
          {% set target_playing = ns.targets | select('in', all_players_playing) | list %}
        {# determine which groups should be resumed becaue a single target is part of that group #}
          {% set ns = namespace(groups = []) %}
            {% for group in all_speaker_groups_playing %}
              {% for entity in speaker_groups[group] if entity in target_playing %}
                {% set ns.groups = ns.groups + [group] %}
              {% endfor %}
            {% endfor %}
          {% set speaker_groups_resume = ns.groups | unique | list %}
        {# determine if target has subgroups which are playing and add to speaker_groups_resume #}
          {% set ns = namespace(groups = []) %}
            {% for target in target_list %}
              {% set ns.groups = ns.groups + 
                  (sub_groups[target] | select('in', all_speaker_groups_playing) | list)
                  if sub_groups is defined else []     
            %}
            {% endfor %}
          {% set speaker_groups_resume = speaker_groups_resume + ns.groups | unique | list %}
        {# determine which single entities are in a group which is going to be resumed #}
          {% set ns = namespace(reject = []) %}
          {% for group in speaker_groups_resume %}
            {% set ns.reject = ns.reject + speaker_groups[group] %}
          {% endfor %}
          {% set reject_list = ns.reject %}
        {# determine which single playing entities are in a group which is a target #}
          {% set target_group = target_list | select('in', speaker_group_list) | reject('in', all_speaker_groups_playing) |list %}
          {% set ns = namespace(single_resume = []) %}
          {% for group in target_group %}
            {% set ns.single_resume = ns.single_resume + speaker_groups[group] | select('in', all_players_playing) | list %}
          {% endfor %}
          {% set single_resume_list = ns.single_resume %}
        {# combine all the above to a list of players which should be resumed #}
          {% set players_resume = (target_playing + speaker_groups_resume + single_resume_list) | reject('in', reject_list) | unique | list %}
          {% set ns = namespace(info=[]) %}
          {% for entity in expand(players_resume) %}
            {% set ns.info = ns.info +  [ 
                                          dict(
                                            entity_id = entity.entity_id,
                                            friendly_name = entity.attributes.friendly_name, 
                                            media_content_id = entity.attributes.media_content_id | default('no media_content'),
                                            media_title = entity.attributes.media_title | default('no title'),
                                            media_artist = entity.attributes.media_artist | default('No artist'),
                                            media_content_type = entity.attributes.media_content_type | default('no type'),
                                            app_name = entity.attributes.app_name | default('no app'),
                                            entity_picture = entity.attributes.entity_picture | default('no pic'),
                                            volume_level = entity.attributes.volume_level | round(2) 
                                            )
                                        ] 
            %}
          {% endfor %}
          {{ ns.info }}
      {% endif %}
  target_not_playing: >
    {% set players_resume_entity = players_to_resume |
    map(attribute='entity_id') | list %} {% set ns = namespace(members = []) %}
    {% for entity in players_resume_entity %}
      {% if entity in speaker_group_list %}
        {% set ns.members = ns.members + speaker_groups[entity] | list %}
      {% endif %}
    {% endfor %} {% set players_resume_all = players_resume_entity + ns.members
    %} {{ target_list | reject('in', players_resume_all) | list }}
  spotify_players_info: >
    {% 
      set spotify_player_list = states.media_player 
                                  | selectattr('state', 'eq', 'playing')
                                  | selectattr('entity_id', 'search', 'media_player.spotify') 
                                  | map(attribute='entity_id') 
                                  | list
    %} {% set entities = expand(spotify_player_list) %} {% set ns =
    namespace(info=[]) %} {% for entity in entities %}
      {% set ns.info = ns.info + [ dict(entity_id=entity.entity_id, source=entity.attributes.source) ] %}
    {% endfor %} {{ ns.info }}

**Comment by TheFes** [comment]
Please download the trace using the download button in the top right corner, and drag the downloaded json to this text box in which you type your message here.

**Comment by besiktas97** [comment]
Well I cant drag and drop the json file, because Github says that they don't support a file type like that.
Is it enough if I copy and paste the info inside the file?

{
  "trace": {
    "last_step": "sequence/7/choose/0/conditions/0",
    "run_id": "2f5c2f610c1f067a2314d73d872bc482",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2022-06-22T11:48:00.048495+00:00",
      "finish": "2022-06-22T11:51:06.966255+00:00"
    },
    "domain": "script",
    "item_id": "google_home_resume",
    "trace": {
      "sequence/0": [
        {
          "path": "sequence/0",
          "timestamp": "2022-06-22T11:48:00.052311+00:00",
          "changed_variables": {
            "fixed_picture": null,
            "speaker_groups": {
              "media_player.alle_boxen": [
                "media_player.woonkamer",
                "media_player.zolder"
              ]
            },
            "default_volume_level": 0.35,
            "this": {
              "entity_id": "script.google_home_resume",
              "state": "off",
              "attributes": {
                "last_triggered": "2022-06-21T21:23:00.042992+00:00",
                "mode": "parallel",
                "current": 0,
                "max": 10,
                "icon": "mdi:cast-audio",
                "friendly_name": "00 🔊 Google Home Resume"
              },
              "last_changed": "2022-06-21T21:26:06.936040+00:00",
              "last_updated": "2022-06-21T21:26:06.936040+00:00",
              "context": {
                "id": "01G642H2ARBN8ZQBCZS96J655V",
                "parent_id": null,
                "user_id": null
              }
            },
            "action": [
              {
                "service": "media_player.play_media",
                "target": {
                  "entity_id": "media_player.alle_boxen"
                },
                "data": {
                  "media_content_id": "http://url_homeassistant/local/azan2.mp3",
                  "media_content_type": "music"
                }
              },
              {
                "service": "media_player.volume_set",
                "target": {
                  "entity_id": "media_player.alle_boxen"
                },
                "data": {
                  "volume_level": 0.5
                }
              }
            ],
            "context": {
              "id": "01G65KV7D4TEVQWFPR7MMKS21Y",
              "parent_id": "01G65KV7CDSM0V0C9861SRG8K6",
              "user_id": null
            }
          }
        }
      ],
      "sequence/1": [
        {
          "path": "sequence/1",
          "timestamp": "2022-06-22T11:48:00.083823+00:00",
          "changed_variables": {
            "target_list": [
              "media_player.alle_boxen"
            ],
            "speaker_group_list": [
              "media_player.alle_boxen"
            ],
            "players_to_resume": [],
            "target_not_playing": [
              "media_player.alle_boxen"
            ],
            "spotify_players_info": []
          },
          "result": {
            "choice": 0
          }
        }
      ],
      "sequence/1/choose/0": [
        {
          "path": "sequence/1/choose/0",
          "timestamp": "2022-06-22T11:48:00.084016+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "sequence/1/choose/0/conditions/0": [
        {
          "path": "sequence/1/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:48:00.084089+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "sequence/1/choose/0/sequence/0": [
        {
          "path": "sequence/1/choose/0/sequence/0",
          "timestamp": "2022-06-22T11:48:00.085192+00:00",
          "result": {
            "params": {
              "domain": "media_player",
              "service": "turn_on",
              "service_data": {},
              "target": {
                "entity_id": [
                  "media_player.alle_boxen"
                ]
              }
            },
            "running_script": false,
            "limit": 10
          }
        }
      ],
      "sequence/1/choose/0/sequence/1": [
        {
          "path": "sequence/1/choose/0/sequence/1",
          "timestamp": "2022-06-22T11:48:00.088968+00:00",
          "result": {
            "delay": 0.25,
            "done": true
          }
        }
      ],
      "sequence/2": [
        {
          "path": "sequence/2",
          "timestamp": "2022-06-22T11:48:00.341958+00:00"
        }
      ],
      "sequence/3": [
        {
          "path": "sequence/3",
          "timestamp": "2022-06-22T11:48:00.345474+00:00",
          "changed_variables": {
            "volume_old_not_playing": [
              {
                "entity_id": "media_player.woonkamer",
                "volume_level": 0.5
              },
              {
                "entity_id": "media_player.zolder",
                "volume_level": 0.5
              }
            ],
            "screen_not_playing": []
          }
        }
      ],
      "sequence/3/repeat/sequence/0": [
        {
          "path": "sequence/3/repeat/sequence/0",
          "timestamp": "2022-06-22T11:48:00.353462+00:00",
          "changed_variables": {
            "repeat": {
              "first": true,
              "index": 1,
              "last": false
            }
          },
          "result": {
            "params": {
              "domain": "media_player",
              "service": "play_media",
              "service_data": {
                "media_content_id": "http://url_homeassistant/local/azan2.mp3",
                "media_content_type": "music",
                "entity_id": [
                  "media_player.alle_boxen"
                ]
              },
              "target": {
                "entity_id": [
                  "media_player.alle_boxen"
                ]
              }
            },
            "running_script": false,
            "limit": 10
          }
        },
        {
          "path": "sequence/3/repeat/sequence/0",
          "timestamp": "2022-06-22T11:48:00.376910+00:00",
          "changed_variables": {
            "repeat": {
              "first": false,
              "index": 2,
              "last": true
            }
          },
          "result": {
            "params": {
              "domain": "media_player",
              "service": "volume_set",
              "service_data": {
                "volume_level": 0.5,
                "entity_id": [
                  "media_player.alle_boxen"
                ]
              },
              "target": {
                "entity_id": [
                  "media_player.alle_boxen"
                ]
              }
            },
            "running_script": false,
            "limit": 10
          }
        }
      ],
      "sequence/4": [
        {
          "path": "sequence/4",
          "timestamp": "2022-06-22T11:48:00.382400+00:00",
          "result": {
            "choice": 0
          }
        }
      ],
      "sequence/4/choose/0": [
        {
          "path": "sequence/4/choose/0",
          "timestamp": "2022-06-22T11:48:00.382601+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "sequence/4/choose/0/conditions/0": [
        {
          "path": "sequence/4/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:48:00.382685+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "sequence/4/choose/0/sequence/0": [
        {
          "path": "sequence/4/choose/0/sequence/0",
          "timestamp": "2022-06-22T11:48:00.383809+00:00",
          "result": {
            "delay": 4,
            "done": true
          }
        }
      ],
      "sequence/5": [
        {
          "path": "sequence/5",
          "timestamp": "2022-06-22T11:48:04.387781+00:00"
        }
      ],
      "sequence/5/choose/0": [
        {
          "path": "sequence/5/choose/0",
          "timestamp": "2022-06-22T11:48:04.388201+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "sequence/5/choose/0/conditions/0": [
        {
          "path": "sequence/5/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:48:04.388378+00:00",
          "result": {
            "result": false,
            "entities": []
          }
        }
      ],
      "sequence/6": [
        {
          "path": "sequence/6",
          "timestamp": "2022-06-22T11:48:04.389256+00:00",
          "result": {
            "choice": 0
          }
        }
      ],
      "sequence/6/choose/0": [
        {
          "path": "sequence/6/choose/0",
          "timestamp": "2022-06-22T11:48:04.389869+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "sequence/6/choose/0/conditions/0": [
        {
          "path": "sequence/6/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:48:04.390180+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "sequence/6/choose/0/sequence/0": [
        {
          "path": "sequence/6/choose/0/sequence/0",
          "timestamp": "2022-06-22T11:48:04.395824+00:00"
        }
      ],
      "sequence/6/choose/0/sequence/0/repeat/sequence/0": [
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/0",
          "timestamp": "2022-06-22T11:48:04.397466+00:00",
          "changed_variables": {
            "repeat": {
              "first": true,
              "index": 1,
              "last": false
            }
          }
        },
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/0",
          "timestamp": "2022-06-22T11:51:06.918750+00:00",
          "changed_variables": {
            "repeat": {
              "first": false,
              "index": 2,
              "last": true
            }
          }
        }
      ],
      "sequence/6/choose/0/sequence/0/repeat/sequence/1": [
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/1",
          "timestamp": "2022-06-22T11:48:04.398213+00:00",
          "changed_variables": {
            "player": {
              "entity_id": "media_player.woonkamer",
              "volume_level": 0.5
            }
          },
          "result": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          }
        },
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/1",
          "timestamp": "2022-06-22T11:51:06.919533+00:00",
          "changed_variables": {
            "player": {
              "entity_id": "media_player.zolder",
              "volume_level": 0.5
            }
          },
          "result": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          }
        }
      ],
      "sequence/6/choose/0/sequence/0/repeat/sequence/2": [
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2",
          "timestamp": "2022-06-22T11:51:06.894402+00:00",
          "changed_variables": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          }
        },
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2",
          "timestamp": "2022-06-22T11:51:06.920154+00:00",
          "changed_variables": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          }
        }
      ],
      "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0": [
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0",
          "timestamp": "2022-06-22T11:51:06.894710+00:00",
          "result": {
            "result": false
          }
        },
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0",
          "timestamp": "2022-06-22T11:51:06.920343+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0/conditions/0": [
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:51:06.894839+00:00",
          "result": {
            "result": false,
            "entities": [
              "media_player.woonkamer"
            ]
          }
        },
        {
          "path": "sequence/6/choose/0/sequence/0/repeat/sequence/2/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:51:06.920441+00:00",
          "result": {
            "result": false,
            "entities": [
              "media_player.zolder"
            ]
          }
        }
      ],
      "sequence/7": [
        {
          "path": "sequence/7",
          "timestamp": "2022-06-22T11:51:06.948124+00:00"
        }
      ],
      "sequence/7/choose/0": [
        {
          "path": "sequence/7/choose/0",
          "timestamp": "2022-06-22T11:51:06.948341+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "sequence/7/choose/0/conditions/0": [
        {
          "path": "sequence/7/choose/0/conditions/0",
          "timestamp": "2022-06-22T11:51:06.948426+00:00",
          "result": {
            "result": false,
            "entities": []
          }
        }
      ]
    },
    "config": {
      "alias": "00 🔊 Google Home Resume",
      "description": "Script for resuming Google Home speakers",
      "icon": "mdi:cast-audio",
      "mode": "parallel",
      "fields": {
        "target": {
          "description": "Enter the targets in case they are not clear from the service calls",
          "required": false,
          "selector": {
            "target": {
              "entity": {
                "integration": "cast",
                "domain": "media_player"
              },
              "device": {
                "integration": "cast"
              }
            }
          }
        },
        "action": {
          "description": "Actions to be performed (only service calls will work)",
          "required": true,
          "selector": {
            "action": null
          }
        }
      },
      "variables": {
        "fixed_picture": null,
        "speaker_groups": {
          "media_player.alle_boxen": [
            "media_player.woonkamer",
            "media_player.zolder"
          ]
        },
        "default_volume_level": 0.35
      },
      "sequence": [
        {
          "alias": "Set variables to be used in the script",
          "variables": {
            "target_list": "{% if voice_tts_target is defined %}\n  {{ [ voice_tts_target ] }}\n{% else %}\n  {

**Comment by TheFes** [comment]
Well, the version you are using is so old that there is no version number mentioned yet.
I added that in version 1.1.0 in February, the script is now on version 2.5.0

If you don't mind I will not spend time in debugging an error in a template which is not even used in the current version anymore.

You can update to the latest version (do note there have been some breaking changes, see the full changelog here https://github.com/TheFes/HA-configuration/blob/main/include/script/00_general/google_cast/docs/changelog_google_home_resume.md)

If you don't want to update, the warning will probably be gone when you use this template `{{ target_not_playing | select('in', players_screen) | list if players_screen is defined and players_screen else [] }}`

**Comment by besiktas97** [comment]
thank you thefes for your comment. Do I need to edit in the script every template where it says: 

- condition: template
            value_template: '{{ screen_not_playing | count > 0 }}'

**Comment by TheFes** [comment]
No, you need to replace:
`{{ [] if not players_screen else target_not_playing | select('in', players_screen) | list }}`
with:
`{{ target_not_playing | select('in', players_screen) | list if players_screen is defined and players_screen else [] }}`

Then `screen_not_playing` will be `[]` and `{{ screen_not_playing | count > 0 }}` will return `false`
