### ISSUE TITLE
Google Nest Hub VS Google Home Mini !

### ISSUE THREAD

**Issue by EmanueleGuidetti** [TheFes/HA-configuration#50]
Hi, 
my compliments for your great work!
I've tray a simple test implementation. This one:

  google_home_voice_test:
    alias: "Google Home Voice Test"
    icon: mdi:car
    sequence:
      - variables:
          message: "Ciao Ciao, ti sto rispondendo da Home Assistant solo qui"
      - alias: "TTS for speaker voice command"
        service: script.google_home_voice
        data:
          use_resume: true
          target_variable: true
          action:
            - alias: "Send TTS message"
              #              service: tts.cloud_say
              service: tts.cloud_say
              data:
                message: "{{ message }}"
          volume: 35

I've made a routine in Google Home App that call this script and reproduce a specific relaxing sound (in according to the title in variable of your script)

I,ve tested from "Google Nest Hub":
- ok google play music
- ok google launch my script

And: the music stop, tts message spoke, the music resume!

I've testes from "Google Home Mini" the same voice command:
- the music stop, i hear a "blip" but no TTS message and no music resume.

If I ask to launch my script without music in playback, the TTS message is reading.

Can you help me, please?
Thanks!

**Comment by TheFes** [comment]
Could you send the trace of an occurrence when it didn't work? I probably need the race of the Google Home voice script and the Google Home resume script

**Comment by TheFes** [comment]
As I received no reply, I will close this issue.
