### ISSUE TITLE
Unable to resume spotify with your scripts.

### ISSUE THREAD

**Issue by blindndangerous** [TheFes/HA-configuration#58]
Hello,
I found your script for resuming spotify on the homeassistant forums.  I think I have everything set up correctly, though I'm getting an error from the google resume helper script and I can't figure out what I've done wrong.
00 - Google Home Resume - Helper Script: If at step 1: Resume needed?: Resume playing: Spotify?: Error executing script. Unexpected error for call_service at pos 2: 'NoneType' object is not subscriptable
I have no idea what this means or how to fix it.  I have your script in scripts.yaml, and I have the automation that goes along with it in automations.yaml.  My automations are in an automations folder and as far as I understand they should be pretty simple.
If you need I can paste my automation to you here.  Either that, or it's something I removed from the script, but all I took out was the groups and the players_screen as I have neither of them. I left primary_spotcast and set it to my name.  Any help you can give would be greatly appreciated.

**Comment by TheFes** [comment]
I'm currently on holiday.
Are you on the most recent version of the script?

Could you provide a trace of both the main script and the helper script.

I will look into it when I'm back at home

**Comment by TheFes** [comment]
@blindndangerous there were issues with Spotcast, so I'm assuming these also caused your issue.
There is a new version of Spotcast releases today.

As you did not reply, or provide a trace, I will close this issue now. If you still have issues after upgrading Spotcast, you can create a new issue. Please provide the traces then.
