### ISSUE TITLE
google_home_resume.yaml  missing?

### ISSUE THREAD

**Issue by freijn** [TheFes/HA-configuration#66]
Hello,

very interested in your work but the file google_home_resume.yaml is missing. 
It gives me an 404  :-(

https://github.com/TheFes/HA-configuration/blob/main/include/script/00_general/google_cast/google_home_resume.yaml

Google found it under : 
https://github.com/TheFes/HA-configuration/blob/main/include/integrations/packages/google_cast/google_home_resume.yaml

**Comment by TheFes** [comment]
That's the right one, made a lot of changes in the last days, and didn't change all links yet

More information can be found here: 
https://github.com/TheFes/HA-configuration/blob/main/include/integrations/packages/google_cast/docs/google_home_resume.md

**Comment by TheFes** [comment]
Links on this page are updated now. If you found the incorrect link on another page, please let me know
https://github.com/TheFes/HA-configuration/tree/main/include/script/00_general/google_cast
