### ISSUE TITLE
' Incorrect type. Expected "object". ' on fresh installation.

### ISSUE THREAD

**Issue by Kagey-cmd** [TheFes/HA-configuration#71]
On a fresh installation of the google_cast package, I see three errors in the google_home_resume.yaml code.
At line 720: `data: "{{ data }}"`
Line 976: `{{ service_data if player.spotcast == 'primary_account' else dict(service_data, **account_data) }}`
Line 1317: `data: "{{ data }}"`

All three locations give _"Incorrect type. Expected "object"._ in the Visual Studio Code Server add-on IDE.

**Comment by TheFes** [comment]
The code is correct, VSCode is incorrect.
The Home Assistant extension for VSCode is not aware that it is allowed to use a template for the entire `data:` section in a service call.
