### ISSUE TITLE
[suggestion] Too Good To Go notification: open direct link

### ISSUE THREAD

**Issue by bavala3010** [TheFes/HA-configuration#75]
Hi,

A suggestion.

You can change the clickAction in the Too Good To Go notification in order to directly open the page of the shop. 

In the file tgtg_alert.yaml
change:
            clickAction: "app://com.app.tgtg"
to:
            clickAction: "{{ state_attr('sensor.tgtg_bakker_ochtend_box', 'Item URL') }}"

**Comment by TheFes** [comment]
Ah, nice, thanks! 
Will change this immediately :)

I made it a bit more generic in case I will ever add a box
`clickAction: "{{ trigger.to_state.attributes['Item URL'] }}"`

**Comment by TheFes** [comment]
https://github.com/TheFes/HA-configuration/commit/86f52ea8b31787f82319803d8d9f1ca604d3ba1b

**Comment by TheFes** [comment]
https://github.com/TheFes/HA-configuration/commit/da22e50e7c22af165386f0d793d114aadc069b33

I made the title for the message variable as well based on the entity which triggered the automation.
