### ISSUE TITLE
Can't choose Sonos media player

### ISSUE THREAD

**Issue by KM192** [TheFes/HA-configuration#80]
I have Sonos media player, capable to stream music, radios, tts, etc. in the same way as google cast devices.
When I tr to setup resume automation I have only google cast devices on the select menu. 
Does this script work with other than google cast devices ?

**Comment by TheFes** [comment]
The selector is limited to the cast integration. 
You can try to add the correct entity in the yaml mode, however, there is a specific Sonos snapshot feature which you can use to create a snapshot before the TTS and  restore afterwards

**Comment by KM192** [comment]
Thanks. I got it.
