### ISSUE TITLE
Question about google speaker groups when i stop a group member all speakers stop.

### ISSUE THREAD

**Issue by pbvdven** [TheFes/HA-configuration#82]
Sorry its not directly related to your google resume script but after i implemented your script i noticed that i could not stop one speaker from playing in a speaker group anymore because all the speaker would stop. i know for sure that 2 maybe 3 weeks ago it did work. So or i did something wrong or this behaviour just change with a ha core update. i cant find anyone mentioning this issue. i also add a vid explaining my issue its a example with mini mediacard "beneden" is my google home created speaker group and group members below i want to stop "woonkamer voor" but then all speakers stop.  https://user-images.githubusercontent.com/39600990/227800177-c26ec451-2475-44e9-a218-4b3df1766f1a.MOV

**Comment by TheFes** [comment]
That has been the way it worked for years for me. Stopping a member of a groups which was playing, would stop the entire group.
I don't think it is related to HA. I always assumed this is just how the Google Home groups work.
