### ISSUE TITLE
Google Home Resume - Error

### ISSUE THREAD

**Issue by mac1secure** [TheFes/HA-configuration#87]
Hi TheFes,

Hope all is well.  Reaching out to you for help on Google Home Resume.  Apparently the error I am seeing is with Google Home Resume - Helper Script.  The error seems to indicate the following: "error": "Could not get spotify token.",  Should I refresh the token or reinstall spotify although seems to be working fine, the integration doesn't appear to be throwing any errors?  Please advise.  [https://www.dpaste.org/6eDch](url)

Thank you,

~Michael

**Comment by TheFes** [comment]
This is not an error coming from the script, but from the `spotcast.start` service call used to resume Spotify. I would suggest to retrieve the tokens again, and reconfigure spotcast
