### ISSUE TITLE
Ceil in plaats van ceiling in round(0, 'ceiling')

### ISSUE THREAD

**Issue by casakampa** [TheFes/HA-configuration#88]
Bij het testen van jouw code ontdekte ik dat _ceiling_ niet gebruikt kan worden binnen _round()_.

> Round the number to a given precision. The first parameter specifies the precision (default is 0), the second the rounding method:
>  *  'common' rounds either up or down
>  *  'ceil' always rounds up
>  *  'floor' always rounds down
>
> If you don’t specify a method 'common' is used.

[Link](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.round)

https://github.com/TheFes/HA-configuration/blob/3657f2dea763be1c8e55569a58053be6240769fb/include/template/trigger/trash_formatted_date.yaml#L35

https://github.com/TheFes/HA-configuration/blob/3657f2dea763be1c8e55569a58053be6240769fb/include/template/trigger/trash_formatted_date.yaml#L37

**Comment by TheFes** [comment]
Thanks, and fixed.
Although I wonder if I should actually use `'common'`  then, as that was the result now.
