### ISSUE TITLE
Updated from 2023.2.1 to 2023.6.1 and its not working resume script is not working

### ISSUE THREAD

**Issue by pbvdven** [TheFes/HA-configuration#98]
I updated the script not because i had issues but just because i thought before i get issues. but after i updated the package file all below this line..... restarted home assistant but now the automations dont work anymore i only use tts option this is the part of my autiomation that calls tts.

It wont do anything it stops the playing music but after that silent the music also doesnt come back when i go back to 2023.2.1 works perfectly again.

anything i can do to solve this issue or provide more info please let me know.

service: script.turn_on
target:
  entity_id: script.google_home_resume
data:
  variables:
    action:
      - alias: Send TTS message
        service: tts.google_say
        target:
          entity_id: media_player.alle_speakers
        data:
          message: "Fietsenberging geopend"
          cache: true
          language: nl
        extra:
          volume: 0.7

**Comment by TheFes** [comment]
Please put the code between code tags (there is a button for it in the GUI `<>`)
I will need traces to see what is going wrong here.
See: https://github.com/TheFes/HA-configuration/tree/main/include/integrations/packages/google_cast#questionsissuesbugsfeature-requests

**Comment by TheFes** [comment]
As I received no further comments, and also recently released version 2023.8.0 I close this issue for now.
If you still have problems, please open a new issue and add traces.
